spring:
  profiles:
    active: dev
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888/
      label: dev/Alisher

  config:
    import: optional:configserver:http://localhost:8888/